[Mejora]: Implementación de la interfaz gráfica del proyecto
ericknavarro/InterpreteSencilloIronyCS pull request #11
Opened 2020-01-30 17:52 UTC by Luiskr1993

Implementación de interfaz gráfica del proyecto, la cual cuenta con una sección para escribir código, una ventana de visualización de resultados al código ejecutado, una sección que simula la consola donde se indican los procesos de ejecución del programa. También se pueden cargar archivos y guardar archivos respectivamente.

2020-01-30 20:39 UTC, rjanixz requested changes
@Luiskr1993 te pido unos cambios sencillos en los comentarios, básicamente es quitar el código completamente del repositorio en lugar de dejarlo comentado, y quitar espacios innecesarios en archivos ya que esto genera conflicto con otros pull requests, especialmente los archivos que no tienen ninguna otra modificación como por ejemplo el archivo Gramatica.cs

2020-01-30 20:39 UTC, rjanixz commented on InterpreteSencillo/InterpreteSencillo/Program.cs
> +            //Sintactico sintac = new Sintactico();
quitar código comentado, es una mala práctica

2020-01-30 20:39 UTC, rjanixz commented on InterpreteSencillo/InterpreteSencillo/analizador/Gramatica.cs
> +
quitar espacios innecesarios, genera conflictos de merge con otros pull requests

2020-01-30 20:39 UTC, rjanixz commented on InterpreteSencillo/InterpreteSencillo/arbol/Imprimir.cs
> +            //return impresion;
quitar código comentado, es una mala práctica

2020-01-30 20:39 UTC, rjanixz commented on InterpreteSencillo/InterpreteSencillo/arbol/Instruccion.cs
> +
quitar espacios innecesarios

2020-02-03 19:01 UTC, Luiskr1993 commented
Gracias @rjanixz acabo de corregir los errores indicados. Y realice el commit con los cambios implementados.

2020-02-03 23:35 UTC, rjanixz approved these changes
Excelente, muchas gracias!

2020-02-23 02:56 UTC, ericknavarro commented
Muchas gracias por tu aporte Luis Carlos.

2020-02-23 02:56 UTC, closed without merging