manejo errores sintacticos, generacion de reporte de errores, 201700314
ericknavarro/InterpreteSencilloIronyCS pull request #12
Opened 2020-01-31 02:33 UTC by carlosE17

resolucion al issue que describi entorno al manejo de errores, como se puede observar al momento de encontrar errores dentro del codigo analizado se genera un html de errores, y aborta la ejecucion del mismo.

El analizador utiliza los simbolos de ";" y de "}"  para recuperarse de errores.

2020-02-02 05:48 UTC, rjanixz requested changes
@carlosE17 te agradezo por tu propuesta. Te voy a solicitar 2 cambios.

Primero, subir solo los cambios necesarios para la solución de tu propuesta, quitar todos los cambios innecesarios de espacios y mover simbolos como las llaves de una línea a otra, ya que esto genera conflictos con otros pull request. te dejo unos ejemplos:

![image](https://user-images.githubusercontent.com/6462555/73603803-f6488400-454c-11ea-9056-8d9da23dc162.png)

Segundo, la propuesta del reporte está bien, pero debe estar aislada del código del análisis sintáctico, esto es para mantener el código ordenado y sea fácil de mantener. Te sugiero que crees una clase que se encargue de toda esta funcionalidad. Esta clase puede ser una utilería, con un método, posiblemnete estático que reciba la lista de errores (si hubiera) y genere el reporte a partir de allí.

De este modo mantendremos el proyecto ordenado.

Cualquier consulta, a las ordenes.

2020-02-02 15:59 UTC, carlosE17 commented
listo, si comparas con el original del ingeniero las llaves ya estan en su lugar correspondiente, asi mismo se separo la implementacion del manejo de errores en una clase aparte

https://github.com/ericknavarro/InterpreteSencilloIronyCS/compare/master...carlosE17:manejoErrores201700314?expand=1

2020-02-23 02:49 UTC, ericknavarro commented
Estimado @carlosE17 
Agradezco mucho tu aporte, y @rjanixz  agradezco mucho todo tu apoyo revisando los cambios de los alumnos, solo me gustaría pedirte un cambio más @carlosE17 , por favor modifica el nombre manejoErrores.cs por ManejoErrores.cs para ceñirnos a la nomenclatura manejada en el resto del proyecto, lo mismo para los otros nombres de tus modificaciones en los que esté presente este escenario.
Saludos cordiales.

2020-02-23 02:49 UTC, ericknavarro commented
Hice un pequeño merge por algunos conflictos que se daban con otros PR a los que hay había hecho merge con el master.

2020-02-28 00:05 UTC, rjanixz commented
@carlosE17 podrías revisar el cambio solicitado por el Ingeniero por favor?

Saludos

2020-02-28 00:36 UTC, carlosE17 commented
> 
> 
> @carlosE17 podrías revisar el cambio solicitado por el Ingeniero por favor?
> 
> Saludos

lo he estado intentando, pero a causa de que el repositorio local que tengo es distinto al del ingeniero no me ha dejado hacer el push, intente hacer un pull y un merge, pero me tira que no es posible porque tengo archivos a los que no se les a hecho merge

disculpen los problemas, pero no tengo mucha experiencia con github, y estoy tratando de aprender

2020-02-28 00:38 UTC, rjanixz commented
@carlosE17 puedes llegar a DSI si  necesitas ayuda. Con gusto te ayudo

2020-02-28 00:42 UTC, carlosE17 commented
> 
> 
> @carlosE17 puedes llegar a DSI si necesitas ayuda. Con gusto te ayudo

gracias, el sabado que hay horario de DSI, te llego a preguntar

2020-02-29 21:44 UTC, carlosE17 commented
creo que ya esta arreglado, por favor revisar que este correcto

2020-03-03 04:32 UTC, rjanixz approved these changes

2020-03-03 04:32 UTC, merged